theme: minima
title: from bnb import website
author: Brian Balsamo
email: brian@brianbalsamo.com
github_username: bnbalsamo
twitter_username: bnbalsamo
description: Librarian, Developer, etc.
collections:
    presentations:
        output: true
    speaker_notes:
        output: true
exclude:
    - tasks.py 
    - Dockerfile
    - .dockerignore
    - .travis.yml
    - README.md
