theme: minima
title: from bnb import website
author: Brian Balsamo
email: brian@brianbalsamo.com
github_username: bnbalsamo
twitter_username: bnbalsamo
description: Librarian, Developer, etc.
collections:
    presentations:
        output: true
exclude:
    - make_post.sh
    - make_pres.sh
defaults:
    -
        - scope:
            - path: ""
            - type: "posts"
        - values:
            layout: "post"
    -
        - scope:
            - path: ""
            - type: "presentations"
        - values:
            layout: "presentation"
    -
        -scope:
            -path: ""
            -type: "drafts"
        -values:
            layout: "post"
